# Generated by Django 5.2.8 on 2025-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name', 'ingredients', 'instructions'], name='recipe_reci_name_4add7a_idx'),
        ),
    ]
